# Generated by Django 3.1.6 on 2021-03-01 17:12
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.translations.utils


def create_default_lang(apps, schema_editor):
    Language = apps.get_model('translations', 'Language')
    Language.objects.get_or_create(code=settings.DEFAULT_LANGUAGE,
                                   defaults={'name': settings.TRANSLATIONS_BASE_LANGUAGE[1]})


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('flag', models.ImageField(blank=True, default='', upload_to='languages')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Technical name.', max_length=255, unique=True)),
                ('message_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('language', models.ForeignKey(default='lt', on_delete=django.db.models.deletion.CASCADE,
                                               to='translations.language')),
                ('message',
                 apps.translations.utils.TranslatableResourceForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                                        related_name='translations',
                                                                        to='translations.message')),
            ],
            options={
                'unique_together': {('message', 'language')},
            },
        ),
        migrations.RunPython(create_default_lang, reverse_code=migrations.RunPython.noop),
    ]
