image:
  file: gitpod.Dockerfile
vscode:
  extensions:
    - batisteo.vscode-django
    - ms-python.python
    - ms-azuretools.vscode-docker
    - dotjoshjohnson.xml
    - mhutchie.git-graph
    - ms-toolsai.jupyter
tasks:
  - name: Start background services
    command: >
      make start-databases &&
      while ! pg_isready -h localhost -U django -d django -p 9432 -q && [[ ${RETRY:=0} -lt 5 ]]; do sleep 5 && RETRY=$((RETRY + 1)); done &&
      make migrate &&
      python manage.py createsuperuser --noinput
    env:
      DJANGO_SUPERUSER_EMAIL: test@test.com
      DJANGO_SUPERUSER_PASSWORD: test
ports:
  - port: 9432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
