version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: django
        ports:
            - "9432:5432"
    redis:
        image: redis
