version: '3'
volumes:
    data:
services:
    postgres:
        image: postgis/postgis:14-3.4-alpine
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: django
        volumes:
            - "data:/var/lib/postgresql/data"
        ports:
            - "9432:5432"
    redis:
        image: redis
        ports:
            - "6379:6379"
    django:
        # image: registry.gitlab.com/corner-case-technologies/<project subgroup>/<repo>/runner:stable
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
        command: ./entrypoint.sh
        ports:
            - "8000:8000"
        environment:
            DJANGO_SUPERUSER_EMAIL: test@test.com
            DJANGO_SUPERUSER_PASSWORD: test
            DJANGO_SETTINGS_MODULE: conf.settings_test
            DB_NAME: django
            DB_USER: django
            DB_PASSWORD: django
            DB_HOST: postgres
            DB_PORT: 5432
            RUN_MODE: "DEVELOPMENT"
            REDIS_URL: "redis://redis:6379/0"
        env_file:
          - .env
        depends_on:
            - postgres
            - redis
