version: '3'
services:
    django:
        build: ./backend
        volumes:
            - ./backend:/app
            - ./backend/media:/media
            - ./frontend:/frontend
            - ./frontend/dist:/static
            - ./frontend/dist/assets.json:/app/assets.json
        command: ./bin/test.sh
        ports:
            - "8082:8082"
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_TEST}
        depends_on:
            - db
