version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: django
            POSTRES_PASSWORD: django
    django:
        build:
            context: ./backend
            dockerfile: Dockerfile-production
        ports:
            - "8082:8082"
        environment:
            DJANGO_SETTINGS_MODULE: conf.settings_test
        depends_on:
            - db
	redis:
		image: redis
