version: '3'
services:
    django:
        build: ./backend
        volumes:
            - ./backend:/app
            - ./backend/media:/media
        command: ./bin/test.sh
        ports:
            - "8082:8082"
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_TEST}
            DB_PASSWORD: django
        depends_on:
            - db
