version: '3'
volumes:
    data:
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: django
            POSTRES_PASSWORD: django
        volumes:
            - data:/var/lib/postgresql/data
    django:
        build:
            context: ./backend
            dockerfile: Dockerfile-production
        environment:
            DJANGO_SETTINGS_MODULE: conf.settings_prod
            DB_NAME: django
            DB_USER: django
            DB_HOST: db
            DB_PORT: 5432
        volumes:
            - ./data:/data:ro
            - "./logs/app:/tmp/logs/app"
            - "./logs/gunicorn:/tmp/logs/gunicorn"
        restart: always
        depends_on:
            - db
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - django
        ports:
            - "80:80"
        volumes:
            - "./backend/media:/media"
            - "./logs/nginx:/tmp/logs"
        restart: always
