apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  DJANGO_SETTINGS_MODULE: conf.settings_qa
  BUILD_VERSION: "${CI_PIPELINE_ID}"
  RUN_MODE: QA
  DB_USER: psql
  DB_HOST: postgresql
  REDIS_URL: redis://redis:6379/0
  DB_NAME: django
  PGPASSWORD: django
  DB_PORT: "5432"
  CI_ENVIRONMENT_URL: ${CI_ENVIRONMENT_URL}
  CI_PROJECT_NAME: ${CI_PROJECT_NAME}
  DJANGO_SUPERUSER_EMAIL: test@test.com
  DJANGO_SUPERUSER_PASSWORD: test
  SENTRY_URL: "${SENTRY_URL}"
  ENVIRONMENT: "${ENVIRONMENT}"
