# Generated by Django 3.1.4 on 2020-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200913_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
