# Generated by Django 4.2.2 on 2023-11-08 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(max_length=3)),
                ("overview", models.TextField()),
                ("title", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("source", models.CharField(max_length=255)),
                ("is_audio", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserTours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Started", "Started"), ("Finished", "Finished"), ("New", "New")],
                        default="New",
                        max_length=8,
                    ),
                ),
                ("tour", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="tours.tour")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TourSite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sites.site")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tours.tour")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tour",
            name="sites",
            field=models.ManyToManyField(through="tours.TourSite", to="sites.site"),
        ),
    ]
