# Generated by Django 4.2.2 on 2023-11-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserTours",
            new_name="UserTour",
        ),
        migrations.AlterField(
            model_name="tour",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tours",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
