# Generated by Django 4.2.2 on 2023-11-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audio",
            old_name="file",
            new_name="url",
        ),
    ]
