# Generated by Django 4.2.2 on 2023-11-19 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0002_rename_usertours_usertour_alter_tour_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="SharedPrivateTour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_tour",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_private_tour",
                        to="tours.usertour",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
