# Generated by Django 4.2.2 on 2023-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_rename_file_audio_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audio",
            old_name="credits",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="credits",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="siteimage",
            old_name="credits",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="credits",
            new_name="source",
        ),
        migrations.AddField(
            model_name="basesite",
            name="title",
            field=models.CharField(default="no_title", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="toursite",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
