# Generated by Django 4.2.2 on 2023-11-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
        ("tours", "0003_rename_credits_audio_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basesite",
            name="city",
        ),
        migrations.RemoveField(
            model_name="city",
            name="country",
        ),
        migrations.RemoveField(
            model_name="site",
            name="author",
        ),
        migrations.RemoveField(
            model_name="site",
            name="base_site",
        ),
        migrations.RemoveField(
            model_name="siteimage",
            name="base_site",
        ),
        migrations.RemoveField(
            model_name="sitetag",
            name="site",
        ),
        migrations.RemoveField(
            model_name="sitetag",
            name="tag",
        ),
        migrations.AddField(
            model_name="tour",
            name="sites",
            field=models.ManyToManyField(through="tours.TourSite", to="sites.site"),
        ),
        migrations.AlterField(
            model_name="toursite",
            name="site",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sites.site"),
        ),
        migrations.AlterField(
            model_name="toursite",
            name="tour",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tours.tour"),
        ),
        migrations.DeleteModel(
            name="Audio",
        ),
        migrations.DeleteModel(
            name="BaseSite",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
        migrations.DeleteModel(
            name="SiteImage",
        ),
        migrations.DeleteModel(
            name="SiteTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
