# Generated by Django 4.2.2 on 2023-11-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_tour_is_private_sharedprivatetour"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="finished_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertour",
            name="is_finished_once",
            field=models.BooleanField(default=False),
        ),
    ]
