# Generated by Django 4.2.2 on 2023-11-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_tour_finished_count_usertour_is_finished_once"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="price",
        ),
        migrations.RemoveField(
            model_name="usertour",
            name="price",
        ),
    ]
