version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 25
    pull-request-branch-name:
      prefix: "dependabot"
      separator: "/"
    schedule:
      interval: weekly
      time: "06:00"
      timezone: Europe/Vilnius
      day: friday
