# Generated by Django 4.2.2 on 2023-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
