# Generated by Django 4.2.2 on 2023-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_rename_usertours_usertour_alter_tour_author"),
        ("users", "0002_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owned_tours",
            field=models.ManyToManyField(related_name="owned_by_users", through="tours.UserTour", to="tours.tour"),
        ),
    ]
