# Generated by Django 4.2.2 on 2023-11-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_wallet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="wallet",
            new_name="balance",
        ),
    ]
