# Generated by Django 4.2.2 on 2023-11-17 07:27

from django.db import migrations, models


def populate_data(apps, schema_editor):
    sites = apps.get_model('sites', 'Site')

    for site in sites.objects.all():
        site.title = site.base_site.title
        site.save(update_fields=['title'])


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="title",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ), migrations.RunPython(populate_data),
    ]
