# Generated by Django 4.2.2 on 2023-11-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="title",
            field=models.CharField(default="unknown_title", max_length=255),
        ),
    ]
