# Generated by Django 4.2.2 on 2023-11-18 22:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_site_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="basesite",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
