# Generated by Django 4.2.2 on 2023-11-19 21:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_transfer_longitude_latitude_into_location_field_custom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basesite",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="basesite",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="basesite",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
